name: cCard_example
description: Demonstrates how to use the contact_card package - a dart port of vCard JS by Eric J Nesser.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  contact_card:
    path: ../
  

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
